# This is a generated file. Not intended for manual editing.
services:
  moviecatalog.api:
    build:
      context: "C:\\Users\\bojan\\OneDrive\\Desktop\\Cinemax\\Cinemax"
      dockerfile: "Services/MovieCatalog.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/MovieCatalog.API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "moviecatalog.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\bojan\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\bojan\\OneDrive\\Desktop\\Cinemax\\Cinemax\\Services\\MovieCatalog.API:/app:rw"
    - "C:\\Users\\bojan\\OneDrive\\Desktop\\Cinemax\\Cinemax:/src:rw"
    working_dir: "/app"
