services:
  identitydb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MATF12345
    ports:
      - "1433:1433"
    volumes:
      - identity_mssql_data:/var/opt/mssql

  identity.api:
    image: identity.api
    build:
      context: .
      dockerfile: Security/IdentityServer/Dockerfile
    depends_on:
      - identitydb
  paymentdb:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MATF12345
      POSTGRES_DB: PaymentDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
  
  moviecatalogdb:
    image: mongo

  moviecatalog.api:
    image: moviecatalog.api
    build:
      context: .
      dockerfile: Services/MovieCatalog.API/Dockerfile
  
  
  payment.api:
    image: payment.api
    build:
      context: .
      dockerfile: Payment.API/Dockerfile

  basketdb:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine

  basket.api:
    image: basket.api
    build:
      context: .
      dockerfile: Services/Basket.API/Dockerfile

  email.api:
    image: email.api
    build:
      context: .
      dockerfile: Email.API/Dockerfile

  privatesession.api:
    image: privatesession.api
    build:
      context: .
      dockerfile: Services/PrivateSessions/PrivateSession/Dockerfile

volumes:
  postgres_data:
  pgadmin_data:
  mongo_data:
  identity_mssql_data:
