services:
  moviecatalogdb:
    container_name: moviecatalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:\data\db
  
  moviecatalog.api:
    container_name: movieCatalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DataBaseSettings:ConnectionString=mongodb://moviecatalogdb:27017"
    depends_on:
      - moviecatalogdb
    ports:
      - "8000:8080"