version: '3.4'

services:
    identitydb:
        container_name: identitydb
        restart: always
        ports:
            - "1433:1433"
        # SA password and EULA handled in base compose

    identity.api:
        container_name: identity.api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ConnectionStrings:IdentityConnectionString=Server=identitydb;Database=IdentityDb;User Id=SA;Password=MATF12345;TrustServerCertificate=true"
        depends_on:
            - identitydb
        ports:
            - "4000:8080"
    #  paymentdb:
    #    container_name: paymentdb
    #    environment:
    #      - POSTGRES_USER=admin
    #      - POSTGRES_PASSWORD=admin1234
    #      - POSTGRES_DB=PaymentDb
    #    restart: always
    #    ports:
    #      - "5432:5432"
    #    volumes:
    #      - postgres_data:/var/lib/postgresql/data

    pgadmin:
        container_name: pgadmin
        environment:
            - PGADMIN_DEFAULT_EMAIL=dev@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=admin1234
        restart: always
        ports:
            - "5050:5080"
        volumes:
            - pgadmin_data:/root/.pgadmin

    

    moviecatalogdb:
        container_name: moviecatalogdb
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:\data\db

    moviecatalog.api:
        container_name: movieCatalog.api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "DataBaseSettings:ConnectionString=mongodb://moviecatalogdb:27017"
            # JWT Settings - Must match Identity API settings
            - "JwtSettings:secretKey=MyVerySecretMessageWhichIsVeryVeryLongAndCannotBeBroken"
            - "JwtSettings:validIssuer=Cinemax identity"
            - "JwtSettings:validAudience=Cinemax"
        depends_on:
            - moviecatalogdb
        ports:
            - "8000:8080"

    payment.api:
        container_name: payment.api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ConnectionStrings:PaymentConnectionString=Host=paymentdb;Port=5432;Database=PaymentDb;Username=postgres;Password=MATF12345;"
            # Redis Cache Settings
            - "CacheSettings:ConnectionString=basketdb:6379"
            # Email Settings
            - "EmailSettings:Mail=vida33085@gmail.com"
            - "EmailSettings:Password=kmfu haci tnno kjqd"
            # PayPal Settings
            - "PayPal:ClientId=AbwOUURIy30Sv997qpH0-Xzwb-rKENp64r2-F8jJx-GNMHcQ9ZFIwvQLjP2-sMe7-u-kg2AGAjjKtGSk"
            - "PayPal:ClientSecret=EP--0kzPAWPT9yg5or-0qKVMWnjusLoqZ-aSIBWhtMouaWcbyORFvfXPPKKCNU77rzq4LHA_d_D9OvI7"
            # JWT Settings
            - "JwtSettings:secretKey=MyVerySecretMessageWhichIsVeryVeryLongAndCannotBeBroken"
            # Email API
            - "EmailApi:BaseUrl=http://email.api:8080"
        depends_on:
            - paymentdb
            - basketdb
            - email.api
        ports:
            - "8004:8080"

    basketdb:
        container_name: basketdb
        restart: always
        ports:
            - "6379:6379"

    rabbitmq:
        container_name: rabbitmq
        restart: always
        ports:
            - 5672:5672
            - 15672:15672

    basket.api:
        container_name: basket.api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "CacheSettings:ConnectionString=basketdb:6379"
            - "GrpcSettings:PaymentServiceUrl=http://payment.api:8080"
            - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
            # JWT Settings - Must match Identity API settings
            - "JwtSettings:secretKey=MyVerySecretMessageWhichIsVeryVeryLongAndCannotBeBroken"
            - "JwtSettings:validIssuer=Cinemax identity"
            - "JwtSettings:validAudience=Cinemax"
        depends_on:
            - basketdb
            - rabbitmq
            - payment.api
        ports:
            - "8001:8081"

    email.api:
        container_name: email.api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ConnectionStrings:RabbitMQ=amqp://guest:guest@rabbitmq:5672"
            - "EmailSettings:SmtpServer=smtp.gmail.com"
            - "EmailSettings:SmtpPort=587"
            - "EmailSettings:Mail=vida33085@gmail.com"
            - "EmailSettings:Password=kmfu haci tnno kjqd"
            - "EmailSettings:SmtpUsername=vida33085@gmail.com"
            - "EmailSettings:SmtpPassword=kmfu haci tnno kjqd"
            - "EmailSettings:FromEmail=vida33085@gmail.com"
            - "EmailSettings:FromName=Cinemax System"
            - "EmailSettings:EnableSsl=true"
        depends_on:
            - rabbitmq
        ports:
            - "8006:8080"

    privatesession.api:
        container_name: privatesession.api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            # JWT Settings - Must match Identity API settings
            - "JwtSettings:secretKey=MyVerySecretMessageWhichIsVeryVeryLongAndCannotBeBroken"
            - "JwtSettings:validIssuer=Cinemax identity"
            - "JwtSettings:validAudience=Cinemax"
            # Google Drive Settings
            - "GoogleDrive:CredentialsPath=cinemax-475115-7345803004e9.json"
            - "GoogleDrive:FolderId=1MZlZG7ikum_H_Hizys5gvK0A-wz1SEq4"
            - "GoogleDrive:ApplicationName=Cinemax Private Sessions"
            # Payment API Settings
            - "PaymentApi:BaseUrl=http://payment.api:8080"
        depends_on:
            - payment.api
        ports:
            - "8005:8080"