version: '3.4'

services:
#  paymentdb:
#    container_name: paymentdb
#    environment:
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=admin1234
#      - POSTGRES_DB=PaymentDb
#    restart: always
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
  
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
        
  paymentdb:
    container_name: paymentdb
    environment:
      - SA_PASSWORD=MATF12345
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - paymentdb_data:/var/opt/mssql/data