version: '3.4'

services:
    #  paymentdb:
    #    container_name: paymentdb
    #    environment:
    #      - POSTGRES_USER=admin
    #      - POSTGRES_PASSWORD=admin1234
    #      - POSTGRES_DB=PaymentDb
    #    restart: always
    #    ports:
    #      - "5432:5432"
    #    volumes:
    #      - postgres_data:/var/lib/postgresql/data

    pgadmin:
        container_name: pgadmin
        environment:
            - PGADMIN_DEFAULT_EMAIL=dev@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=admin1234
        restart: always
        ports:
            - "5050:5080"
        volumes:
            - pgadmin_data:/root/.pgadmin

    

    moviecatalogdb:
        container_name: moviecatalogdb
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:\data\db

    moviecatalog.api:
        container_name: movieCatalog.api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "DataBaseSettings:ConnectionString=mongodb://moviecatalogdb:27017"
        depends_on:
            - moviecatalogdb
        ports:
            - "8000:8080"

    payment.api:
        container_name: payment.api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ConnectionStrings:PaymentConnectionString=Host=paymentdb;Port=5432;Database=PaymentDb;Username=postgres;Password=MATF12345;"
        depends_on:
            - paymentdb
        ports:
            - "8004:8080"

    basketdb:
        container_name: basketdb
        restart: always
        ports:
            - "6379:6379"

    rabbitmq:
        container_name: rabbitmq
        restart: always
        ports:
            - 5672:5672
            - 15672:15672

    basket.api:
        container_name: basket.api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "CacheSettings:ConnectionString=basketdb:6379"
            # - "GrpcSettings:DiscountUrl=http://discount.grpc"
            - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
        depends_on:
            - basketdb
            - rabbitmq
        ports:
            - "8001:8081"
