services:
  paymentdb:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MATF12345
      POSTGRES_DB: PaymentDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
  
  moviecatalogdb:
    image: mongo

  moviecatalog.api:
    image: moviecatalog.api
    build:
      context: .
      dockerfile: Services/MovieCatalog.API/Dockerfile
  
  
  payment.api:
    image: payment.api
    build:
      context: .
      dockerfile: Payment.API/Dockerfile

  basketdb:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine

  basket.api:
    image: basket.api
    build:
      context: .
      dockerfile: Services/Basket.API/Dockerfile

volumes:
  postgres_data:
  pgadmin_data:
  mongo_data:
  sql-edge_data:
